### ISSUE TITLE
0.7 problems

### ISSUE THREAD

**Issue by lingyunQAQ** [ShadowOxygen/OxygenX#40]
I can use it in the morning, why is this problem now?

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\OxygenX-master\OxygenX-0.7.py", line 967,
 in <module>
    Main()
  File "C:\Users\Administrator\Desktop\OxygenX-master\OxygenX-0.7.py", line 161,
 in __init__
    self.start_checker()
  File "C:\Users\Administrator\Desktop\OxygenX-master\OxygenX-0.7.py", line 849,
 in start_checker
    print(self.announcement)
AttributeError: 'Main' object has no attribute 'announcement'

**Comment by ShadowOxygen** [comment]
Will be fixed in 0.8

**Comment by lingyunQAQ** [comment]
> 将固定在0.8

About when? Because I can't use 0.7 right now
